/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:b2479e84-9fe7-4595-8c8e-672996946a13",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_Js9Dr1RvU",
    "aws_user_pools_web_client_id": "7qsf2ndfnn9uaq2kc5sngk6eab",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "soundwaveb5d3f0888a6e4004a01a59a253a3e3dc05ac0-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1",
    "aws_dynamodb_all_tables_region": "ap-south-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "SoundwaveSongs-dev",
            "region": "ap-south-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "musicapi",
            "endpoint": "https://a2hla1rrob.execute-api.ap-south-1.amazonaws.com/dev",
            "region": "ap-south-1"
        }
    ]
};


export default awsmobile;
